# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.9)
{
  description = "Tulips microblog";
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*.tar.gz";
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.0.tar.gz";
  };

  outputs = { self, flake-schemas, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in
    {
      schemas = flake-schemas.schemas;
      formatter = forEachSupportedSystem ({ pkgs }: pkgs.nixpkgs-fmt);
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            go_1_20
            nixpkgs-fmt
            hugo
          ];
          env = {
            CGO_ENABLE = "0";
          };
        };
      });
    };
}
